# GitHub Action that uses Ruff to format and lint the Python code in an incoming push request.

name: Run Ruff
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: 'x64'
      - run: pip install ruff
      - run: ruff check . --fix
      - run: ruff format --check .
      - name: If needed, commit ruff changes to a new pull request
        if: failure()
        run: |
          ruff format .
          git config --global user.name autoruff_push
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git commit -am "fixup! Format Python code with ruff"
          git push